# Generated by Django 2.2.1 on 2019-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_Id', models.CharField(max_length=16)),
                ('Shift', models.CharField(max_length=16)),
                ('Date', models.DateField()),
                ('Age', models.CharField(max_length=16)),
                ('Primary_Fur_Color', models.CharField(max_length=128)),
                ('Location', models.CharField(max_length=128)),
                ('Specific_Location', models.CharField(max_length=128)),
                ('Running', models.NullBooleanField()),
                ('Chasing', models.NullBooleanField()),
                ('Climbing', models.NullBooleanField()),
                ('Eating', models.NullBooleanField()),
                ('Foraging', models.NullBooleanField()),
                ('Other_Activities', models.CharField(max_length=128)),
                ('Kuks', models.NullBooleanField()),
                ('Quaas', models.NullBooleanField()),
                ('Moans', models.NullBooleanField()),
                ('Tail_flags', models.NullBooleanField()),
                ('Tail_twitches', models.NullBooleanField()),
                ('Approaches', models.NullBooleanField()),
                ('Indifferent', models.NullBooleanField()),
                ('Runs_from', models.NullBooleanField()),
            ],
        ),
    ]
