# Generated by Django 2.2.7 on 2019-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.CharField(max_length=16),
        ),
    ]
